### ISSUE TITLE
bigint: Failed to load bindings, pure JS will be used (try npm run rebuild?)

### ISSUE THREAD

**Issue by fukaoi** [atonoy/solana-suite#88]
＊It is occurring at a certain point in time.
＊Need to research

**Comment by fukaoi** [comment]
Maybe it's the content of this article.

https://github.com/trufflesuite/ganache/issues/1080#issuecomment-906550239

**Comment by Vince489** [comment]
I just got the same error following a tutorial.

**Comment by wiggledom** [comment]
same error here

**Comment by fukaoi** [comment]
Hi @Passionist59 

This issue is fixed in @solana/web3.js. So it should not show up in solana-suite.
At what point are you getting this error?

**Comment by wiggledom** [comment]
Yeah, I 'm using @solana/web3.js
But I have not ever received that error before
I have found that issues today
Do I update @solana/web3.js? or that issues will be removed automatically?
Wouldn't that cause anything else to happen?

**Comment by saurabhsri108** [comment]
@solana/web3.js is up to date for me yet the same issue. Tried using npm or yarn, doesn't work. Same error in build.
